(defvar temp)
(defun f-l-swap (l)
    (setf temp (last3 l))
    (switch-last l (car l))
    (setf (car l) temp)
    (print l)
)
(defun switch-last (list4 last)
    (cond 
        ((null list4) nil)
        ((null (cdr list4)) (setf (car list4) last))
        (t (switch-last (cdr list4) last))
    )
)
(defun last3 (list)
    (cond 
        ((null list) nil)
        ((null (cdr list)) (car list))
        (t (last3 (cdr list)))
    )
)
(f-l-swap '(a b c))
